services:
  database:
    build:
      context: ./database
    container_name: bastiondesk-postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init-sql:/docker-entrypoint-initdb.d
    networks:
      - bastiondesk-net-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 4s
      timeout: 4s
      retries: 5

  llm_service:
    build:
      context: ./llm_service
    env_file:
      - .env
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    networks:
      - bastiondesk-net-internal
      - bastiondesk-net-external
    deploy:
      resources:
        limits:
          memory: 10GB

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: ["bun", "run", "start"]
    ports:
      - "3333:3333"
    networks:
      - bastiondesk-net-internal

  nginx:
    build:
      context: ./nginx
    container_name: bastiondesk-nginx
    ports:
      - "4567:4567"
    networks:
      - bastiondesk-net-internal
      - bastiondesk-net-external

volumes:
  postgres-data:
    driver: local
  huggingface-cache:
    driver: local

networks:
  bastiondesk-net-internal:
    driver: bridge
  bastiondesk-net-external:
    driver: bridge
