services:
  database:
    build:
      context: ./database
    container_name: securedesk-postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init-sql:/docker-entrypoint-initdb.d
    networks:
      - securedesk-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER:-zglosto_user} -d ${POSTGRES_DB:-zglosto_db}"]
      interval: 4s
      timeout: 4s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  securedesk-net:
    driver: bridge
